### PR TITLE
Migration to netstandard/.net6, multiple languages and custom project dictionary support

### PR DESCRIPTION
**Pull request by rpsft**
- Migrated to .Net 6, netstandard2.0
- Removed VSIX project
- Added multiple dictionary handling (languages can be added on a per-directory basis)
- Added file based configuration (`.wecantspell` or `.wecantspell.json` JSON file in directory) like following:
```json
{
    "isRoot" : true,
    "languages" : [
        "en-US",
        "ru-RU"
    ]
}
```
- Added support for local project dictionaries. One can put a file named `.directory.dic`, `.spelling.dic` or `.wecantspell.dic` in Hunspell format in directory and words will be added to spell checking.
- Added codefix "Add word to project dictionary"

### CODE REVIEW

**Comment by aarondandy** [comment]
This looks like a fork and not an actual PR. If you are going to fork it, do it! This code hasn't been touched in ... 6 years. Also this codebase is effectively abandoned and should be archived. At this point, it's best to just start over. There is probably good stuff in this PR but to be totally honest I don't have time to review this.

**Comment by rpsft** [comment]
You're right, this is going to be a significant change and might be better supported in a fork. Do you mind if we continue with naming "WeCantSpell" as we proceed to version 2.0 and publish to nuget?

**Comment by aarondandy** [comment]
I don't think I claimed the prefix on nuget and it looks like you have claimed `WeCantSpell.Roslyn` already. Go for it!

**Comment by aarondandy** [comment]
This might be worth a look too if you haven't seen it yet: https://learn.microsoft.com/en-us/visualstudio/ide/text-spell-checker?view=vs-2022#how-to-customize-the-spell-checker

**Comment by shokurov** [comment]
I am aware of the Visual Studio spell checker. The reason i need an analyser is twofold:
1. We need a centralised quality control at build time with static analysis
2. The team uses different tools and we need to keep a centralised dictionary to be used by both JetBrains and Visual Studio

I think the idea of sharing common configuration in .editorconfig is great. Did you think of how to avoid ambiguity between the values used by Visual Studio for indicating specific checks done vs Roslyn codes severity used by analyser?

**Comment by aarondandy** [comment]
> Did you think

Definitely not 😆

**Comment by aarondandy** [comment]
This PR has become a full fork: https://github.com/rpsft/WeCantSpell.Roslyn

**Pull request closed without merging**
